name: Report a bug
description: "Report something that's broken."
body:
  - type: markdown
    attributes:
      value: "We're sorry to hear you have a problem. Can you help us solve it by providing the following details."
  - type: input
    attributes:
      label: Package version
      description: What version of our Package are you running? Please be as specific as possible
      placeholder: 2.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Laravel version
      description: Provide the Laravel version that you are using. [Please ensure it is still supported.](https://laravel.com/docs/releases#support-policy)
      placeholder: 10.4.1
    validations:
      required: true
  - type: input
    attributes:
      label: PHP version
      description: Provide the PHP version that you are using.
      placeholder: 8.1.4
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide detailed steps to reproduce your issue.
    validations:
      required: true
      